#!/bin/bash

# initialize variables
dataset_id=""
run_id=""
output_dir="SegData"

# Parse command line arguments
while getopts ":d:r:" opt; do
  case $opt in
    d) dataset_id=$OPTARG ;;
    r) run_id=$OPTARG ;;
    \?) echo "Invalid option: -$OPTARG" >&2; exit 1 ;;
    :) echo "Option -$OPTARG requires an argument." >&2; exit 1 ;;
  esac
done

# Check if both -d (dataset_id) and -r (run_id) were provided
if [ -z "$dataset_id" ] || [ -z "$run_id" ]; then
    echo "Usage: $0 -d <dataset_id> -r <run_id>"
    exit 1
fi

# Get the directory of the script
script_dir=$(dirname "$(realpath "$0")")
# download the tomogram
echo "Downloading tomogram..."
target_file=$(python "$script_dir/auto_tomo_download.py" "$dataset_id" "$run_id")

# Run the conversion script )
echo "Running mrc_to_mha.py to convert $target_file..."
python "$script_dir/mrc_to_mha.py" "$target_file"

# Check if the conversion was successful
if [ $? -ne 0 ]; then
    echo "Error: mrc_to_mha.py failed to convert $target_file."
    exit 1
fi

# Determine the output file path
output_file="$output_dir/$(basename "${target_file%.*}.mha")"

# Open the output file with itksnap
echo "Opening $output_file with itksnap..."
itksnap "$output_file"

# Check if itksnap was successful
if [ $? -ne 0 ]; then
    echo "Error: itksnap failed to open $output_file."
    exit 1
fi

echo "Process completed successfully."